authors:
  jxnl:
    name: Jason Liu
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/4852235?v=4
    url: https://twitter.com/intent/follow?screen_name=jxnlco
  sergiobayona:
    name: Sergio Bayona
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/155783?v=4
    url: https://twitter.com/intent/follow?screen_name=sergiobayona
